name: squid_v1.5-star2.7.0f
channels:
  - bioconda
  - conda-forge
dependencies:
  - squid=1.5
  - bioconda::star=2.7.0f
  - bioconda::samtools=1.9
  - conda-forge::python=3.7.1
  - conda-forge::numpy=1.15.4
